"""empty message

Revision ID: 0caccd4fcf36
Revises: 7a41d599988c
Create Date: 2024-10-25 19:33:37.389492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0caccd4fcf36'
down_revision = '7a41d599988c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Text(length=11),
               existing_nullable=False)

    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.INTEGER(),
               type_=sa.Text(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.Text(length=11),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.Text(length=11),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
