"""empty message

Revision ID: 2b4c8b508f75
Revises: fc9582dd315a
Create Date: 2025-02-11 21:24:08.787862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4c8b508f75'
down_revision = 'fc9582dd315a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritadas',
    sa.Column('aluno_ra', sa.Text(), nullable=False),
    sa.Column('vaga_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_ra'], ['alunos.ra'], ),
    sa.ForeignKeyConstraint(['vaga_id'], ['vagas.id'], ),
    sa.PrimaryKeyConstraint('aluno_ra', 'vaga_id')
    )
    op.create_table('selecionados',
    sa.Column('aluno_ra', sa.Text(), nullable=False),
    sa.Column('vaga_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_ra'], ['alunos.ra'], ),
    sa.ForeignKeyConstraint(['vaga_id'], ['vagas.id'], ),
    sa.PrimaryKeyConstraint('aluno_ra', 'vaga_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selecionados')
    op.drop_table('favoritadas')
    # ### end Alembic commands ###
