"""empty message

Revision ID: 7a41d599988c
Revises: d5f222b0f23c
Create Date: 2024-10-25 12:18:41.726328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a41d599988c'
down_revision = 'd5f222b0f23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vagas', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vagas', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
