"""empty message

Revision ID: ccab39a840ee
Revises: 16a665530a3c
Create Date: 2024-12-02 18:53:52.171834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccab39a840ee'
down_revision = '16a665530a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vagas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bolsa_valor', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vagas', schema=None) as batch_op:
        batch_op.drop_column('bolsa_valor')

    # ### end Alembic commands ###
