"""empty message

Revision ID: ce67e510d987
Revises: 
Create Date: 2024-10-21 18:27:55.704790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce67e510d987'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('professores',
    sa.Column('ra', sa.Text(length=8), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ra')
    )
    op.create_table('alunos',
    sa.Column('ra', sa.Text(length=8), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome_do_curso', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['nome_do_curso'], ['cursos.nome'], ),
    sa.PrimaryKeyConstraint('ra')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alunos')
    op.drop_table('professores')
    op.drop_table('cursos')
    # ### end Alembic commands ###
