"""empty message

Revision ID: e001a1384fd5
Revises: f8f8ee1238f7
Create Date: 2024-11-01 18:06:50.325322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e001a1384fd5'
down_revision = 'f8f8ee1238f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ADMS',
    sa.Column('adm_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('cpf', sa.Text(length=11), nullable=False),
    sa.PrimaryKeyConstraint('adm_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ADMS')
    # ### end Alembic commands ###
